// <auto-generated />
namespace QuanLyVeSo.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Update_NgayKetThuc_GiaVeSo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update_NgayKetThuc_GiaVeSo));
        
        string IMigrationMetadata.Id
        {
            get { return "201812180324559_Update_NgayKetThuc_GiaVeSo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
